name: CheckLabel
on:
  pull_request:
    types: ['labeled', 'unlabled']

jobs:
  MergeNG:
    runs-on: [ubuntu-latest]
    steps:
      - if: contains(github.event.pull_request.labels.*.name, 'Merge NG')
        run: false
